version: '3'
services:
  streamlit:
    image: 'minutes-generate-app'
    env_file:
     - .env
    volumes:
      - type: volume
        source: video
        target: /app
    ports:          
      - 8501:8501

volumes:
  video: